"""new fields in user model

Revision ID: 308eafe2196d
Revises: d9c8b29cde56
Create Date: 2023-03-27 12:18:13.700804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308eafe2196d'
down_revision = 'd9c8b29cde56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
